language: python
install:
  - pip install -U pip
  - pip install tox
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pep8
  - TOX_ENV=coverage

script: tox -e $TOX_ENV

notifications:
  email:
    - swistakm@gmail.com
